version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: crud_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: crud_backend
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: crud_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
